INSERT INTO company (NAME, BALANCE, MODIFIER) VALUES ('CROZ', '1000', 1);
INSERT INTO company (NAME, BALANCE, MODIFIER) VALUES ('FER', '2000', 2);
INSERT INTO userAccount (NAME, PASSWORD, ROLE, BALANCE, REQUESTSAVAILABLE, COMPANY_ID) VALUES ('admin', 'admin', 'admin', 1337, 68, 1);
INSERT INTO userAccount (NAME, PASSWORD, ROLE, BALANCE, REQUESTSAVAILABLE, COMPANY_ID) VALUES ('user', 'user', 'user', 0, 2, 2);

INSERT INTO log (USERNAME, DESCRIPTION, TIME) VALUES ('user', 'test log description', TO_DATE('17/12/2077', 'DD/MM/YYYY'));

INSERT INTO token (MARK, VALUE, BEGINDATE, ENDDATE, ACTIVATED, OWNER_ID) VALUES ('1231234444', 10,  TO_DATE('17/12/2077', 'DD/MM/YYYY'),  TO_DATE('17/11/2077', 'DD/MM/YYYY'), 1, 2);
INSERT INTO token (MARK, VALUE, BEGINDATE, ENDDATE, ACTIVATED, OWNER_ID) VALUES ('1231235555', 10,  TO_DATE('17/12/2077', 'DD/MM/YYYY'),  TO_DATE('17/11/2077', 'DD/MM/YYYY'), 0, 2);

INSERT INTO tokengenerationrequest (ID, USERID, USERNAME) VALUES ('1', '2', 'user');

